name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Ejecutar cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: lessslie
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.8.0
        with:
          branch: output
          message: 'Generate Snake'
          add: 'dist'
          push: origin output --force
          github_token: ${{ secrets.GITHUB_TOKEN }}
